apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-native
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  template:
    spec:
      containers:
        - name: demo-native
          image: thomasvitale/demo-native-devoxx:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "756Mi"
              cpu: "0.2"
            limits:
              memory: "756Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: demo-native